# Generated by Django 4.2.4 on 2023-08-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Time Stamp in UTC')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='home.store')),
            ],
        ),
    ]
